name: Draft release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build release
        run: |
          echo "Tag is created: $GITHUB_REF_NAME"
          source ./scripts/common.sh
          docker pull $BUILD_IMAGE
          ./ul build-release $GITHUB_REF_NAME

      - name: Make draft GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.tar.gz
            *.deb
